name: ChestShop
main: muqsit\chestshop\ChestShop
api: 3.0.0
version: 4
commands:
  blackmarket:
    aliases: ["cs", "bmarket"]
permissions:
  chestshop.command.opcmd:
    default: op
  chestshop.command.add:
    default: op
  chestshop.command.remove:
    default: op
